<a href="https://colab.research.google.com/github/Rao-Ashu/numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python objectives:**
<br>
-> containers: lists(costless insertion and append),
<br>
-> dictionaries(fast lookup)

**Numpy provides:**
<br>
1. extension package to python for multi-dimensional arrays
2. closer to hardware(efficiency)
3. Array oriented computing

# **CREATING A NUMPY ARRAY**

In [ ]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [ ]:
#Simple python lists
l = range(1000)
%timeit [i**2 for i in l]

297 µs ± 4.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
l1 = np.arange(1000)
%timeit l1**2

1.48 µs ± 366 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# 1-D array
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [ ]:
# print dimensions
a.ndim

1

In [ ]:
# shape
a.shape

(4,)

In [ ]:
# 2-D,
b = np.array([[0,1,2],[3,4,5]])
b



array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.ndim


2

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b) #returns the size of the first dimension

2

In [ ]:
# 3-D array
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
len(c)

2

**Other ways to create numpy arrays**

In [ ]:
a = np.arange(0,10,2) #start, end, step
a

array([0, 2, 4, 6, 8])

In [ ]:
# using linspace(linear space function)
b = np.linspace(0,1,6)  #start, end, number of points
b

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# common arrays
a = np.ones((3,3)) #function arguement is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3) #returns a 2-D array with 1's in diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# create a diagonal array
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a) #extract diagonal

array([1, 2, 3, 4])

In [ ]:
# Creating array using random
a = np.random.rand(4)
a

array([0.44101132, 0.19270716, 0.81421392, 0.34377181])

In [ ]:
a = np.random.randn(4)
a

array([ 0.27770326, -0.71761656, -1.11320063,  0.245728  ])

NOTE:
<br>
In some arrays elements are like 1. instead of 1, because of data-type

In [ ]:
a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [ ]:
# can explicitly specify the data-type
a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# **3. INDEXING AND SLICING**

In [ ]:
a = np.arange(10)
print(a[5])

5


In [ ]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [ ]:
a[2,1] = 5 # assignment of value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**SLICING**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] #[startIndex : endIndex(exclusive) : step]

array([1, 3, 5, 7])

In [ ]:
# combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning in previous array a
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# **4. COPIES AND VIEWS**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)

True

here numpy array 'a' and 'b' shares the memory using the VIEW concept, that means both the pointers a,b are pointing to same location.

In [ ]:
b[0] = 11
b

array([11,  2,  4,  6,  8])

In [ ]:
a # 11 will be at the 0th index of array a also as same memory location


array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
#instead do force copy
a = np.arange(10)

c = a[::2].copy()  #force a copy
c

array([0, 2, 4, 6, 8])

In [ ]:
c[0] = 10
a
# it will not make changes in a as separate copy due to force copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **5. FANCY INDEXING**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. It creates copies not views.

In [ ]:
a = np.random.randint(0,20,15)
a

array([ 5,  0, 14, 13, 13,  4, 13,  6, 17,  7,  6, 19,  1, 19, 13])

In [ ]:
mask = (a%2 ==0) #boolean expression

In [ ]:
b = a[mask]
b

array([ 0, 14,  4,  6,  6])

In [ ]:
c = a
c[mask] = -1
c

array([ 5, -1, -1, 13, 13, -1, 13, -1, 17,  7, -1, 19,  1, 19, 13])

**Indexing with an array of integers**

In [ ]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Indexing with an array of integers, same index is repeated
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [ ]:
# assign new values too
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

### NUMERICAL OPERATIONS ON NUMPY

In [57]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [58]:
a**2

array([ 1,  4,  9, 16])

In [59]:
b = np.ones(4)
a-b             #operations happen elementwise

array([0., 1., 2., 3.])

In [60]:
# Matrix Multiplicaiton
c = np.diag([1,2,3,4])
print(c*c)
print ("*********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [61]:
from binascii import b2a_base64
a = np.array([1,2,3,4])
b = np.array([2,2,4,4])
a == b

array([False,  True, False,  True])

In [62]:
#array-wise comparison
a = np.array([1,2,3,4])
b = np.array([2,2,4,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [63]:
# Logical Operation

a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

**Shape Mismatch**

In [64]:
a = np.arange(5)
a + np.array([1,2])

ValueError: ignored

In [65]:
a = np.arange(10)
np.sum(a)

45

In [68]:
# Sum by rows and by column
a = np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [69]:
a.sum(axis=0) #column first dimension

array([3, 3])

In [70]:
a.sum(axis = 1) #rows(second dimension)

array([2, 4])

**Other Reductions**

In [71]:
x = np.array([1,3,2])
x.min()

1

In [72]:
x.max()

3

In [73]:
x.argmax() # gives index of minimum element

1

In [74]:
x.argmin() #index of maximum element

0

**Logical Operator**

In [75]:
np.all([True, True, False])

False

In [76]:
np.any([True, True, False])

True

**STATISTICS**

In [77]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [78]:
np.median(x)

1.5

In [79]:
np.median(y, axis=-1) #last axis

array([2., 5.])

**EXAMPLE**

In [80]:
# load data into numpy array object
data = np.loadtxt('populations.txt')

In [81]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [84]:
year, monkey, dog, cat = data.T #columns to variable
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [85]:
population = data[:,1:] #take all rows and column from 1 to last
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [86]:
# find index of max population species each year
np.argmax(population, axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

## **BROADCASTING**

In [8]:
a = np.tile(np.arange(0,40,10),(3,1))  # copy 3 times rowwise and 1 time entire row
print(a)

print("************")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [6]:
import numpy as np
b = np.tile(np.arange(0,10,2),(3,2))  # copy 3 times rowwise and 2 time entire row
print(b)

[[0 2 4 6 8 0 2 4 6 8]
 [0 2 4 6 8 0 2 4 6 8]
 [0 2 4 6 8 0 2 4 6 8]]


In [9]:
c = np.array([1,2,3])
a+c
# here c uses the broadcasting and become the size of a

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

**Converting 1D array to 2D**

In [10]:
 a = np.arange(0,40,10)
 a.shape

(4,)

In [11]:
a = a[: , np.newaxis] #add new axis -> 2D array
a.shape

(4, 1)

In [13]:
a

array([[ 0],
       [10],
       [20],
       [30]])

## **Array Shape Manipulation**

**FLATTENING**

In [15]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() #return a flattened array,(1D)

array([1, 2, 3, 4, 5, 6])

In [16]:
a #don't change the real array

array([[1, 2, 3],
       [4, 5, 6]])

**Reshaping**
<br>
The inverse operation to flattening

In [18]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [19]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [20]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# reshape may return a copy!
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 100
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Sorting Data**

In [23]:
# Sorting along an axis
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis =1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [24]:
#inplace sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [26]:
# Sorting using fancy Indexing
a = np.array([4,3,1,2])
b = np.argsort(a)
b

array([2, 3, 1, 0])

In [27]:
a[b]

array([1, 2, 3, 4])